kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: binding
  namespace: hemang-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: roles
subjects:
- kind: User
  namespace: hemang-namespace
  name: <User Principal Name>
/* When you are using AD group, you have to write Group and replace UPN with group object ID */
